# Dichotomie

<!-- TODO Expliquer le proncipe général de la dichotomie -->

<!-- TODO Remarques sur la complexité -->

## Recherche par dichotomie dans un tableau triée

Lorsque l'on dispose d'une tableau trié, on peut proposer un algorithme de recherche dans un tableau efficace en utilisant le principe de **dichotomie**.

- On recherche tout d'abord l'élément "central" de ce tableau.
- Si c'est l'élément recherché, on s'arrête. Sinon, on le compare à l'élément recherché.
- Si l'élément recherché est inférieur à l'élément central, on le recherche dans la première partie du tableau. Sinon, on le recherche dans la deuxième partie du tableau.
- On retourne donc à la première étape de notre algorithme appliqué à l'un des deux "demi-tableaux".

```{python}
def appartient_dicho(elt, tab):
    g = 0
    d = len(tab) - 1
    while g <= d:
        m = (g + d) // 2
        if tab[m] == elt:
            return True
        if elt < tab[m]:
            d = m - 1
        else:
            g = m + 1
    return False
```

```{python}
appartient_dicho(13, [1, 3, 5, 7, 8, 10, 13, 14, 17, 19])
```

```{python}
appartient_dicho(18, [1, 3, 5, 7, 8, 10, 13, 14, 17, 19])
```

Comme souvent, un dessin vaut mieux qu'un long discours. On donne deux exemples d'application de cet algorithme.

```{python}
#| echo: false
%run scripts/recherche_dicho.py
```

```{python}
# | echo: false
# | warning: false
from random import randint
from manim import tempconfig

with tempconfig(
    {
        "quality": "low_quality",
        "output_file": "recherche_dicho_succes",
        "verbosity": "ERROR",
    }
):
    recherche_dicho_succes = RechercheDicho([1, 3, 7, 8, 10, 13, 14, 17, 19], 13)
    recherche_dicho_succes.render()
```

```{python}
# | echo: false
from IPython.display import Video

Video(recherche_dicho_succes.renderer.file_writer.movie_file_path, embed=True)
```

```{python}
# | echo: false
# | warning: false
from random import randint
from manim import tempconfig

with tempconfig(
    {
        "quality": "low_quality",
        "output_file": "recherche_dicho_echec",
        "verbosity": "ERROR",
    }
):
    recherche_dicho_echec = RechercheDicho([1, 3, 7, 8, 10, 13, 14, 17, 19], 18)
    recherche_dicho_echec.render()
```

```{python}
# | echo: false
from IPython.display import Video

Video(recherche_dicho_echec.renderer.file_writer.movie_file_path, embed=True)
```

On peut proposer une version qui renvoie l'indice de la première occurence de l'élément recherché plutôt qu'un booléen.

```{python}
def indice_dicho(elt, tab):
    g = 0
    d = len(tab) - 1
    while g <= d:
        m = (g + d) // 2
        if tab[m] == elt:
            return m
        if elt < tab[m]:
            d = m - 1
        else:
            g = m + 1
    return None
```

```{python}
indice_dicho(13, [1, 3, 7, 8, 10, 13, 14, 17, 19])
```

```{python}
print(indice_dicho(18, [1, 3, 7, 8, 10, 13, 14, 17, 19]))
```

## Exponentiation rapide

Lorsque l'on souhaite calculer $x^n$ où $x$ est un nombre réel et $n$ un entier naturel, on doit a priori effectuer $n-1$ multiplications. Cependant, on peut faire mieux que cela en utilisant le principe de dichotomie. On remarque en effet que :

- Si $n$ est pair, alors $x^n = (x^2)^{\frac{n}{2}}$.
- Si $n$ est impair, alors $x^n = x \cdot (x^2)^{\frac{n-1}{2}}$. 

On peut donc proposer l'algorithme suivant pour calculer $x^n$.

```{python}
def exponentiation_rapide(x, n):
    a = 1
    while n > 0:
        if n % 2 == 1:
            a *= x
        x = x*x
        n //= 2
    return a
```

```{python}
exponentiation_rapide(3, 4)
```

On peut calculer la complexité de cet algorithme. En notant $T(n)$ le nombre de multiplications effectuées par l'algorithme pour calculer $x^n$, on a :

- $T(0) = 0$.
- $T(n) = T((n-1)/2) + 2$ si $n$ est impair.
- $T(n) = T(n/2) + 1$ si $n$ est pair.

On prouve alors que $T(n)=O(\log_2(n))$^[Le lecteur intéressé pourra sé référer au [Master Theorem](https://fr.wikipedia.org/wiki/Master_theorem)], ce qui est bien meilleur que la complexité $O(n)$ de l'algorithme naïf.
