# Algorithmes gloutons

## Rendu de monnaie

Le problème du rendu de monnaie est un exemple classique d'utilisation d'un algorithme glouton. On dispose d'un système de monnaie (pièces ou billets de valeurs déterminées) et on cherche à rendre une somme d'argent à l'aide de cette monnaie.

:::{#exm-rendu-pieces-1}
On dipose de pièces de monnaie de 1€, 2€ et 5€ et on souhaite à totaliser la somme de 23€. On peut par exemple donner 4 pièce de 5€, 1 pièce de 2€ et 1 pièce de 1€. Ce n'est pas la seule possibilité : on aurait aussi pu donner 2 pièces de 5€, 4 pièces de 2€ et 5 pièces de 1€.
:::

Un algorithme glouton consiste alors à toujours rendre une pièce de valeur maximale et inférieure à la somme restant à rendre.

:::{#exm-rendu-pieces-2}
On reprend l'exemple précédent. On dipose de pièces de monnaie de 1€, 2€ et 5€ et on souhaite à totaliser la somme de 23€. On donne alors des pièces de 5€ tant que la somme restant à rendre est inférieure à 5€. On donne donc 4 pièces de 5€. La somme restante est alors de 3€. On donne donc 1 pièce de 2€. La somme restante est de 1€ et on termine donc en donnant 1 pièce de 1€.
:::

```{python}
def rendu_monnaie(somme, pieces):
    pieces_triees = sorted(pieces, reverse=True)
    d = {}
    r = somme
    for piece in pieces_triees:
        q, r = divmod(r, piece)
        d[piece] = q
    return d, r
```

```{python}
rendu_monnaie(23, [1, 2, 5])
```

Il n'est pas toujours possible de rendre la somme suivant le système de monnaie employée. Par exemple, avec des pièces de 3€, 9€ et 12€, on ne pourra atteindre que des sommes qui sont des multiples de 3€.

L'algorithme glouton peut également ne pas trouver de solution alors qu'il en existe une.

```{python}
rendu_monnaie(16, [2, 15])
```

On pourrait ici tout simplement rendre 8 pièces de 2€.

## Allocation de salles

On dispose d'un ensemble de salles et d'un ensemble de cours à programmer. Chaque cours a un horaire de début et un horaire de fin. On souhaite allouer les cours aux salles de manière à ce qu'aucun cours ne se chevauche dans une même salle.

On va s'intéresser à deux problèmes : le premier consiste à allouer le maximum de cours dans une seule salle, le second consiste à allouer tous les cours dans un minimum de salles.

### Allocation d'un maximum de cours dans une salle

L'algorithme glouton consiste à toujours choisir le cours qui se termine le plus tôt parmi les cours disponibles. On peut ainsi maximiser le nombre de cours alloués dans une salle. Par exemple, supposons que l'on dispose des cours suivants déjà triés par heure de fin :

- Mathématiques : 8h-10h
- Physique : 9h-11h
- Chimie : 11h-12h
- Informatique : 11h-13h
- Biologie : 12h-14h
- Histoire : 12h-15h

On examine les cours dans l'ordre :

- on choisit le cours de Mathématiques (8h-10h)
- on ne peut pas choisir le cours de Physique (9h-11h) car il chevauche le cours de Mathématiques
- on choisit le cours de Chimie (11h-12h)
- on ne peut pas choisir le cours d'Informatique (11h-13h) car il chevauche le cours de Chimie
- on choisit le cours de Biologie (12h-14h)
- on ne peut pas choisir le cours d'Histoire (12h-15h) car il chevauche le cours de Biologie

Finalement, on a choisi les cours de Mathématiques, Chimie et Biologie. On a donc alloué 3 cours dans une salle.

Cet algorithme est un algorithme glouton car il choisit toujours le cours qui se termine le plus tôt parmi les cours disponibles. On peut montrer qu'il est optimal dans le sens où il permet d'allouer le maximum de cours dans une salle.

On peut implémenter cet algorithme en Python. Chaque cours est représenté par un tuple (matière, début, fin).

```{python}
def allocation_cours(cours):
    cours_tries = sorted(cours, key=lambda x: x[2])  # Tri par heure de fin
    allocation = []
    dernier_cours_fin = 0

    for cours in cours_tries:
        if cours[1] >= dernier_cours_fin:  # Si le cours ne chevauche pas le dernier cours choisi
            allocation.append(cours)
            dernier_cours_fin = cours[2]

    return allocation
```

Vérifions l'algorithme avec l'exemple précédent :

```{python}
cours = [
    ("Mathématiques", 8, 10),
    ("Physique", 9, 11),
    ("Chimie", 11, 12),
    ("Informatique", 11, 13),
    ("Biologie", 12, 14),
    ("Histoire", 12, 15)
]
allocation_cours(cours)
```
