# Parcours d'un graphe et applications

```{python}
# | echo: false
import networkx as nx
import logging

logging.getLogger("matplotlib.animation").setLevel(logging.WARNING)
```

```{python}
# | echo: false
%run ../scripts/graphe.py
```

## Piles et files

On décrit d'abord deux structures de données que sont les **piles** et les **files** dans lesquelles on peut insérer et retirer des éléments un par un.

### Piles

Une pile est une structure de donnée dont les éléments sont insérés et retirés par le même "côté" comme le montre l'animation suivante.

```{python}
#| echo: false
%run ../scripts/stack.py
```

```{python}
# | include: false
from manim import tempconfig

with tempconfig(
    {"quality": "low_quality", "output_file": "stack", "verbosity": "ERROR"}
):
    stack_movie = Stack()
    stack_movie.render()
```

```{python}
# | echo: false
from IPython.display import Video

Video(stack_movie.renderer.file_writer.movie_file_path, embed=True)
```

Autrement dit, le dernier élément inséré sera le premier à être retiré (dernier arrivé, premier sorti).

Quand on insère un élément dans la pile, on dit qu'on **empile** cet élément ; quand on retire un élément, on dit qu'on le **dépile**.

On peut simuler le comportement d'une pile à l'aide de listes Python.

On empile un élément à l'aide de la méthode `append`.

```{python}
L = []
L.append('abc')
L.append(42)
L.append('def')
L
```

On dépile un élément à l'aide de la méthode `pop`.

```{python}
L.pop()
```

```{python}
L
```

### Files {#files}


Une file est une structure de donnée dont les éléments sont insérés par un "côté" et retirés par l'autre "côté" comme le montre l'animation suivante.

```{python}
#| echo: false
%run ../scripts/queue.py
```

```{python}
# | include: false
from manim import tempconfig

with tempconfig(
    {"quality": "low_quality", "output_file": "queue", "verbosity": "ERROR"}
):
    queue_movie = Queue()
    queue_movie.render()
```

```{python}
# | echo: false
from IPython.display import Video

Video(queue_movie.renderer.file_writer.movie_file_path, embed=True)
```

Autrement dit, le premier élément inséré sera le premier à être retiré (premier arrivé, premier sorti).

Quand on insère un élément dans la file, on dit qu'on **enfile** cet élément ; quand on retire un élément, on dit qu'on le **défile**.

On peut à nouveau simuler le comportement d'une file à l'aide de listes Python.

On enfile un élément à l'aide de la méthode `append`.

```{python}
L = []
L.append('abc')
L.append(42)
L.append('def')
L
```

On défile un élément à l'aide de la méthode `pop(0)`.

```{python}
L.pop(0)
```

```{python}
L
```

### Problèmes d'efficacité

L'implémentation des listes Python (nous ne rentrerons pas dans les détails) fait que l'appel à la méthode `pop()` se fait en temps **constant** tandis que l'appel à la méthode `pop(0)` se fait en temps **linéaire**.[^lineaire]

[^lineaire]: De manière schématique, une fois que le premier élément de la liste a été supprimé lors de l'appel de `pop(0)`, tous les autres éléments doivent êtres décalés pour combler l'emplacement laissé libre.

Néanmoins, le module `collections` du langage Python dipose d'une classe `deque` (**D**oubled **E**nded **Que**ue) implémentant de manière efficace les piles et les files à la fois.

Un objet de classe `deque` peut représenter une **pile** à l'aide des méthodes `append` et `pop`.

```{python}
from collections import deque

d = deque()
d.append('abc')
d.append(42)
d.append('def')
d
```

```{python}
d.pop()
```

```{python}
d
```

On peut également représenter une **file** à l'aide des méthodes `append` et `popleft()`.

```{python}
from collections import deque

d = deque()
d.append('abc')
d.append(42)
d.append('def')
d
```

```{python}
d.popleft()
```

```{python}
d
```

## Parcours d'un graphe

On élabore des algorithmes permettant de parcourir un graphe, c'est-à-dire de visiter une et une seule fois chacun de ses sommets. Dans ce qui suit, un graphe sera représenté par un dictionnaire de listes d'adjacence. Ceci permet d'avoir rapidement accès aux **voisins** d'un sommet.

:::{#def-voisin}
# Voisin

On appelle **voisin** d'un sommet tout sommet relié à ce sommet par une arête du graphe.
De manière plus formelle, soit $G=(S,A)$ un graphe. On appelle **voisin** d'un sommet $s\in S$ tout sommet $t\in S$ tel que $\{s,t\}\in A$.
:::

Pour simplifier, on supposera par la suite que les graphes considérés sont [**connexes**](graphe.qmd#def-connexite).

### Parcours en profondeur

```{python}
import collections

def parcours_profondeur(G, sommet_initial):
    visites = {sommet : False for sommet in G.keys()}   # Aucun des sommets n'a été visité
    pile = collections.deque()
    pile.append(sommet_initial)                         # Empiler le sommet initial
    while pile:                                         # Tant que la pile n'est pas vide
        sommet = pile.pop()                             # Dépiler un sommet
        if not visites[sommet]:                         # Si le sommet n'est pas visité
            visites[sommet] = True                      # Marquer le sommet comme visité
            print("Sommet "+str(sommet)+" visité")
            for voisin in G[sommet]:                    # Empiler les voisins du sommet
                if not visites[voisin]:                 # s'ils n'ont pas été visités
                    pile.append(voisin)
```

```{python}
G = {1: [2, 3, 4], 2: [1, 3, 4], 3: [1, 2, 3, 5], 4: [1, 2], 5: [3]}
```

```{python}
# | echo: false
Graphe(nx.Graph(G)).get_parcours_profondeur_animation(1)
```

```{python}
parcours_profondeur(G, 1)
```

```{python}
G = {1: [2, 3], 2: [4, 5], 3: [6, 7], 4: [], 5: [], 6: [], 7:[]}
```

```{python}
# | echo: false
Graphe(nx.Graph(G)).get_parcours_profondeur_animation(1)
```

```{python}
parcours_profondeur(G, 1)
```

### Parcours en largeur

```{python}
import collections

def parcours_largeur(G, sommet_initial):
    visites = {sommet : False for sommet in G.keys()}   # Aucun des sommets n'a été visité
    file = collections.deque()
    file.append(sommet_initial)                         # Enfiler le sommet initial
    while file:                                         # Tant que la file n'est pas vide
        sommet = file.popleft()                         # Défiler un sommet
        if not visites[sommet]:                         # Si le sommet n'est pas visité
            visites[sommet] = True                      # Marquer le sommet comme visité
            print("Sommet "+str(sommet)+" visité")
            for voisin in G[sommet]:                    # Enfiler les voisins du sommet
                if not visites[voisin]:                 # s'ils n'ont pas été visités
                    file.append(voisin)
```

```{python}
G = {1: [2, 3, 4], 2: [1, 3, 4], 3: [1, 2, 3, 5], 4: [1, 2], 5: [3]}
```

```{python}
# | echo: false
Graphe(nx.Graph(G)).get_parcours_largeur_animation(1)
```

```{python}
parcours_largeur(G, 1)
```

```{python}
G = {1: [2, 3], 2: [4, 5], 3: [6, 7], 4: [], 5: [], 6: [], 7:[]}
```

```{python}
# | echo: false
Graphe(nx.Graph(G)).get_parcours_largeur_animation(1)
```

```{python}
parcours_largeur(G, 1)
```

### Comparaison des parcours en profondeur et en largeur

Il est plus facile de visualiser la différence entre parcours en profondeur et parcours en largeur dans le cadre des arbres.

```{python}
#| echo: false
%run ../scripts/parcours.py
```

```{python}
# | include: false
from manim import tempconfig

with tempconfig(
    {"quality": "low_quality", "output_file": "parcours_movie", "verbosity": "ERROR"}
):
    parcours_movie = DoubleParcours()
    parcours_movie.render()
```

```{python}
# | echo: false
from IPython.display import Video

Video(parcours_movie.renderer.file_writer.movie_file_path, embed=True)
```


## Applications

### Détection de cycles

Le parcours d'un graphe en profondeur ou en largeur permet de détecter la présence de [cycle](graphe.qmd#def-cycle).

```{python}
import collections

def contient_cycle_profondeur(G, sommet_initial):
    visites = {sommet : False for sommet in G.keys()}
    pile = collections.deque()
    pile.append((sommet_initial, None))
    while pile:
        sommet, parent = pile.pop()
        if not visites[sommet]:
            visites[sommet] = True
            for voisin in G[sommet]:
                if not visites[voisin]:
                    pile.append((voisin, sommet))
                elif parent != voisin:
                    return True
    return False
```

```{python}
import collections

def contient_cycle_largeur(G, sommet_initial):
    visites = {sommet : False for sommet in G.keys()}
    file = collections.deque()
    file.append((sommet_initial, None))
    while file:
        sommet, parent = file.popleft()
        if not visites[sommet]:
            visites[sommet] = True
            for voisin in G[sommet]:
                if not visites[voisin]:
                    file.append((voisin, sommet))
                elif parent != voisin:
                    return True
    return False
```

```{python}
G = {1: [2, 3, 4], 2: [1, 3, 4], 3: [1, 2, 3, 5], 4: [1, 2], 5: [3]}
```

```{python}
# | echo: false
nx.draw_spring(nx.Graph(G), with_labels=True, font_weight="bold", font_size=20, node_size=600)
```

```{python}
contient_cycle_profondeur(G, 1), contient_cycle_largeur(G, 1)
```

```{python}
G = {1: [2, 3], 2: [4, 5], 3: [6, 7], 4: [], 5: [], 6: [], 7:[]}
```

```{python}
# | echo: false
nx.draw_spring(nx.Graph(G), with_labels=True, font_weight="bold", font_size=20, node_size=600)
```

```{python}
contient_cycle_profondeur(G, 1), contient_cycle_largeur(G, 1)
```

### Connexité

Le parcours d'un graphe en profondeur ou en largeur permet de déterminer la [connexité](graphe.qmd#def-connexite).

```{python}
import collections

def connexite_profondeur(G, sommet_initial):
    visites = {sommet : False for sommet in G.keys()}
    pile = collections.deque()
    pile.append(sommet_initial)
    while pile:
        sommet = pile.pop()
        if not visites[sommet]:
            visites[sommet] = True
            for voisin in G[sommet]:
                if not visites[voisin]:
                    pile.append(voisin)
    return False not in visites.values()
```

```{python}
import collections

def connexite_largeur(G, sommet_initial):
    visites = {sommet : False for sommet in G.keys()}
    file = collections.deque()
    file.append(sommet_initial)
    while file:
        sommet = file.popleft()
        if not visites[sommet]:
            visites[sommet] = True
            for voisin in G[sommet]:
                if not visites[voisin]:
                    file.append(voisin)
    return False not in visites.values()
```

```{python}
G = {1: [2, 3, 4], 2: [1, 3, 4], 3: [1, 2, 3, 5], 4: [1, 2], 5: [3]}
```

```{python}
# | echo: false
nx.draw_spring(nx.Graph(G), with_labels=True, font_weight="bold", font_size=20, node_size=600)
```

```{python}
connexite_profondeur(G, 1), connexite_largeur(G, 1)
```

```{python}
G = {1: [2, 3, 4], 2: [1, 3, 4], 3: [1, 2, 3], 4: [1, 2], 5: [6, 7], 6 :[5], 7: [5]}
```

```{python}
# | echo: false
nx.draw_spring(nx.Graph(G), with_labels=True, font_weight="bold", font_size=20, node_size=600)
```

```{python}
connexite_profondeur(G, 1), connexite_largeur(G, 1)
```

<!-- TODO Faire la même chose pour les graphes orientés -->

<!-- TODO Peut-être renvoyer la liste des visités pour parcours -->